before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FQKNWdrQ1TLjW28awf2MEkdy/thVfIwmTb38+GnK5Oio6b+6IdpU90NDsUllp7Lha2w/DUdODMeS4HHHBNZjOZ/JoSFhqBAzy8NA6Ok5ftPyw8zq4vvL7tbUM6EN/Fn9Q+7C2VqYZH8Vzaoay88f0iLKnX3GCP66GL2kynSV5NKGTkEg+DUlpgd5GAdQO1GfeN/ps/Q+XqNSNgdlai10jX657QkU3KBvpLGK0fx08Log14q01g0kWGDJuCV0Kv4Z/poVhn+v3rwZ5MXQtIXLeHSIdxfbyy+naYhxXDEGODt2U6EsJ8EPOHb9Vl+uIHpVGZ7mcDMtZMZ4gF4bfsaSx47HjIeHtl30AJNGJZLWUJDPqW5ns/yyiVZbKEh76J5dthhIt9BYl3kAM7Annj1o5QG9upPvLtl4LrEIkzhsAxAtb6rF1e3qrJK5psSZl3VBqkGDv4JDwn/SwOLOKwoeQKL/XlLE1GoTnHtjmdFiQ5uN5AouhbfAWTMzxuLo+a/72InsUO7cDnscjnT4Oj+Ev7lpZeJfI9wrTbMCwACm/qY52VEpqYqv5uBLtP2YeMTuzjDXRnJuQMmOgY2RMJsJ0r2+iovf8hJ8Hu61s4S3G1KqwxlJTq3f62WpXHytmv8SNhCc7yCRqDGaPpI3WITQ/K4oaXOjhNevSJKkjRn+mdo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
